CREATE TABLE item (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name NVARCHAR(10) NOT NULL,
	code CHAR(5) UNIQUE,
	price INT,
	regdate DATE
);


DROP TABLE item

ALTER TABLE item AUTO_INCREMENT = 1000;
INSERT INTO item VALUES (NULL,'item01',11119,1000, CURRENT_DATE);

SELECT * FROM item