# DDL
CREATE TABLE users(
	ID NVARCHAR(10) PRIMARY KEY,
	PWD NVARCHAR(20),
	NAME NVARCHAR(30)
);


CREATE TABLE items(
	ID INT(10) AUTO_INCREMENT PRIMARY KEY,
	NAME NVARCHAR(20),
	PRICE INT(10),
	RATE FLOAT(10,2),
	REGDATE DATE
);

ALTER TABLE items CHANGE COLUMN  REGDATE REGDATE DATETIME;

SELECT id, CAST(REGDATE AS DATE) FROM items;

INSERT INTO users VALUES ('id01','pwd01','kim') 
ON DUPLICATE KEY UPDATE NAME='lee';
INSERT INTO users (id,pwd,name) VALUES ('id02','pwd02','kim');

INSERT INTO items VALUES (NULL, 'item10', 30000, 3.2, CURRENT_TIMESTAMP(), 'C1');
INSERT INTO items VALUES (NULL, 'item04', 40000, 3.2, CURRENT_DATE());
INSERT INTO items VALUES (NULL, 'item04', NULL, 3.2, CURRENT_DATE(), 'c4');


INSERT INTO items VALUES (NULL, 'item05', 40000, 3.2, CURRENT_DATE()),
(NULL, 'item06', 40000, 3.2, CURRENT_DATE()),
(NULL, 'item07', 40000, 3.2, CURRENT_DATE());

# UPDATE items SET price = price * rate

SELECT * FROM users;
SELECT * FROM items;